### ISSUE TITLE
run offline bag

### ISSUE THREAD

**Issue by woshidaye** [nkuwenjian/slam_karto#1]
First of all, thank you for sharing the code. I installed successfully, I want to run my data bag with your code. How do I do it? I am looking forward to your reply.

**Comment by FabianSchurig** [comment]
Hey @woshidaye,
Just create a launchfile which fits your data. Make sure your `tf` tree is okay and add `static_tf` transforms if needed.

```
<launch>
  <param name="/use_sim_time" value="true" />

  <node pkg="tf" type="static_transform_publisher" name="map_publisher" args="0.0 0 0 0 0 0 base_link laser 100" />

  <node pkg="slam_karto" type="slam_karto" name="slam_karto" output="screen">
    <remap from="scan" to="laser"/>
    <param name="odom_frame" value="odom"/>
    <param name="map_update_interval" value="25"/>
    <param name="resolution" value="0.025"/>
  </node>
  <node name="rviz" pkg="rviz" type="rviz" required="true"
      args="" />
  <!--<node name="playbag" pkg="rosbag" type="play"
      args="clock -r 5 $(arg bag_filename)" />-->
</launch>
```

Then just launch slam_karto
```
roslaunch slam_karto karto_slam.launch
```

and play the rosbag in another terminal
```
rosbag play <yourbagfile> --clock -r <speed default:1>
```

**Comment by nkuwenjian** [comment]
Thank your very much for the useful comment ! @Bitfroest 
I am sorry for not maintainning this repo for a long time. I have uploaded a launch file along with a rosbag file and updated the README file for a simple demonstration.

**Comment by arjunskumar** [comment]
@nkuwenjian unable to find the rosbag file, can you re upload the same ?

**Comment by nkuwenjian** [comment]
@arjunskumar 
Hi, the rosbag file is a little large (more than 10Mb). So I eventually didn't upload it to the github repository. You may download it from the following link
https://www.dropbox.com/s/f1zo9ivlfpmi0lb/intel.bag?dl=0

**Comment by arjunskumar** [comment]
@nkuwenjian Thank you
